version: "3.1"

networks:
  ghost:
    driver: bridge

services:
  ghost:
    image: ghost:5.62
    restart: always
    container_name: ghost_5
    ports:
      - 3030:2368
    volumes:
      - ${GHOST_CONTENT_VOLUME_DIR}:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ${DB_CONNECTION_HOST}
      database__connection__port: ${DB_CONNECTION_PORT}
      database__connection__user: ${DB_CONNECTION_USER}
      database__connection__password: ${DB_CONNECTION_PASSWORD}
      database__connection__database: ${DB_CONNECTION_DATABASE}
      # this url value is just an example, and is likely wrong for your environment!
      url: ${GHOST_URL}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    networks:
      - ghost
