version: "3"

services:
  # app:
  #   container_name: node-app
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "9090:3000"
  #   restart: "on-failure"
  app:
    image: next-ssg-blog:latest
    container_name: node-app
    ports:
      - "9090:3000"
    restart: "on-failure"
networks:
  mynetwork:
    external: true
