version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server-1
    container_name: code-server-1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /Users/userName/Workspace:/config
    ports:
      - 8443:8443
    restart: unless-stopped
# ref : docker-compose.yml https://hub.docker.com/r/linuxserver/code-server
